name: Publish

on:
  push:
    tags: [ v* ]
    
env:
  DOTNET_VERSION: 7.0.x
  
jobs:
  publish:
    if: contains(github.ref, 'tags/v') # works only version tagged
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Publish windows
      run: dotnet publish -p:PublishProfile=FolderWinx64Profile

    - name: Zip Folder windows
      run: zip -r Windows64.zip ./src/Windows64Exe

    - name: Publish linux
      run: dotnet publish -p:PublishProfile=FolderLinux64Profile

    - name: Zip Folder linux
      run: zip -r Linux64.zip ./src/Linux64Exe

    - name: Get Releasetag version
      id: get_release_info
      run: echo ::set-output name=file_name::v${TAG_REF_NAME##*/v}  value=`cat release_url.txt` echo ::set-output name=upload_url::$value
      env:
        TAG_REF_NAME: ${{ github.ref }}
        
    - name: Upload Release Asset windows
      id: upload-release-assetwindows 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: ./Windows64.zip
        asset_name: Windows64.zip
        asset_content_type: application/zip

    - name: Upload Release Asset linux
      id: upload-release-assetlinux 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: ./Linux64.zip
        asset_name: Linux64.zip
        asset_content_type: application/zip
