name: Publish

on:
  push:
    tags: [ v* ]

env:
  DOTNET_VERSION: 7.0.x

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Publish windows
      run: dotnet publish -p:PublishProfile=FolderWinx64Profile

    - name: Publish linux
      run: dotnet publish -p:PublishProfile=FolderLinux64Profile