name: Publish

on:
  push:
    tags: [ v* ]
    
env:
  DOTNET_VERSION: 7.0.x

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Publish windows
      run: dotnet publish -p:PublishProfile=FolderWinx64Profile

    - name: Zip Folder windows
      run: zip -r Windows64.zip ./src/Windows64Exe

    - name: Publish linux
      run: dotnet publish -p:PublishProfile=FolderLinux64Profile

    - name: Zip Folder linux
      run: zip -r Linux64.zip ./src/Linux64Exe
      
    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.3.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
          
    - name: Upload Release Asset windows artefacts
      id: upload-release-asset-windows 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./Windows64.zip
        asset_name: Windows64.zip
        asset_content_type: application/zip

    - name: Upload Release Asset windows artefacts
      id: upload-release-asset-linux
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./Linux64.zip
        asset_name: Linux64.zip
        asset_content_type: application/zip
